name: Pull Request - Build when a pull request is raised against main branch

# 1 - PR open without label => test, build, upload
# 2 - PR open with preview label => test, build, upload, preview deploy
# 3 - PR open with any other label => skip??

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  test-and-build:
    name: Run unit tests and build the app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 21.2
        uses: actions/setup-node@v4
        with:
          node-version: '21.2'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: build

  # deploy-preview:
  #   needs: test-and-build
  #   if: ${{ github.event.label.name == 'preview' }}
  #   name: Publish and deploy preview image to cloud run
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check label
  #       run: echo "${{ toJson(github) }}"
